### ISSUE TITLE
server 

### ISSUE THREAD

**Issue by lordmen99** [TakuSemba/RtmpPublisher#1]
Hi, interest with your project. if i run this https://github.com/TakuSemba/docker-nginx-rtmp

its not need other live streaming server like wowza etc? just setup that server on vps,build android app and start live streaming?

**Comment by TakuSemba** [comment]
yes, if you run [this](https://github.com/TakuSemba/docker-nginx-rtmp) on your vps, you dont need a streming server like wowza.

docker-nginx-rtmp runs [nginx-rtmp-module](https://github.com/arut/nginx-rtmp-module) inside, and receive RTMP stream and also creates HLS playlists and ts files.

**Comment by lordmen99** [comment]
wow, great. sample app can try for live streaming? its low latency?

**Comment by TakuSemba** [comment]
yes you can. when i tried, the latency was 3 or 4 seconds.
I think it could be less using other streaming server or adjusting parameters.

**Comment by lordmen99** [comment]
ok, i will setup it. and how many user watch when other user streaming?

**Comment by TakuSemba** [comment]
well, It depends on your server spec and how you implement the server...

**Comment by lordmen99** [comment]
ok.

**Comment by lordmen99** [comment]
can u help me setup docker in my vps?
