### ISSUE TITLE
Activity 在加载 GLSurfaceView 报这个错

### ISSUE THREAD

**Issue by mixiaodou** [TakuSemba/RtmpPublisher#3]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.opengl.GLSurfaceView$GLThread.surfaceCreated()' on a null object reference

**Comment by mixiaodou** [comment]
Mi phones.Android 7.0;
When the demo is opened to the home page, it may be that millet Miui modifies the system source code

**Comment by TakuSemba** [comment]
> When the demo is opened to the home page, it may be that millet Miui modifies the system source code

sorry. i dont understand what you are saying.
