### ISSUE TITLE
Slow transmission to server

### ISSUE THREAD

**Issue by camillo860** [TakuSemba/RtmpPublisher#7]
The smartphone and server are in LAN and i try with private ip but the transmission is very low, i wait 30 second for view Video on Server.
I try  with AsyncTask for use another thread but i wait more time ( +/- 25 seconds).
When you send package to server, do you use TCP protocol or UDP protocol?.
How accelerate send package and encoding video & audio? 
I need view streaming after max 5 second.

**Comment by TakuSemba** [comment]
when i tried, the latency was about 5 seconds but it may depend on the device you use.

RTMP uses TCP protocol.
please try it with lower bitrate to make it faster.

**Comment by TakuSemba** [comment]
let me know if you still got the problem
